/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.des.spring.generate.dialog;

import com.des.schemadb.SchemaDB;
import com.des.session.Session;
import com.des.spring.generate.frame.JSpringGenerate;
import com.des.spring.generate.frame.Project;
import com.des.spring.generate.frame.SpringGenerator;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Surachai
 */
public class SetupDB extends javax.swing.JFrame {

    private Project mainFrame;
    private static final String Mysql_Name = "Mysql";
    private static final String Sqlserver_Name = "SqlServer";
    public Project getMainFrame() {
        return mainFrame;
    }

    public void setMainFrame(Project mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * Creates new form SetupDB
     */
    public SetupDB() {
        initComponents();
        Vector Items = new Vector();
        Items.add("---- select DB type ----");
        Items.add("SqlServer");
        Items.add("MySQL");
        Items.add("Oracle");
        DefaultComboBoxModel model = new DefaultComboBoxModel(Items);
        listDBSel.setModel(model);
        DriverNameTxt.setEditable(false);
        connectionTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listDBSel = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        DriverNameTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        serverTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkBut = new javax.swing.JButton();
        connectionTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        portTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DBTxt = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        close = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null), "Setup Database"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Type");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        listDBSel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listDBSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDBSelActionPerformed(evt);
            }
        });
        jPanel2.add(listDBSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 27, 262, -1));

        jLabel2.setText("Driver Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 68, -1, -1));
        jPanel2.add(DriverNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 65, 262, -1));

        usernameTxt.setText("username");
        jPanel2.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 106, -1, -1));

        userTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTxtKeyReleased(evt);
            }
        });
        jPanel2.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 103, 262, -1));

        jLabel3.setText("password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 144, -1, -1));

        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        jPanel2.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 141, 262, -1));

        jLabel4.setText("server");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 183, -1, -1));

        serverTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverTxtActionPerformed(evt);
            }
        });
        serverTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serverTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serverTxtKeyReleased(evt);
            }
        });
        jPanel2.add(serverTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 180, 262, -1));

        jLabel5.setText("Connection");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 303, -1, -1));

        checkBut.setText("check");
        checkBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButActionPerformed(evt);
            }
        });
        jPanel2.add(checkBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));
        jPanel2.add(connectionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 300, 262, -1));

        jLabel7.setText("port");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 223, -1, -1));

        portTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                portTxtKeyReleased(evt);
            }
        });
        jPanel2.add(portTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 220, 262, -1));

        jLabel6.setText("database");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 263, -1, -1));

        DBTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBTxtActionPerformed(evt);
            }
        });
        DBTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DBTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DBTxtKeyReleased(evt);
            }
        });
        jPanel2.add(DBTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 260, 262, -1));

        submit.setText("ok");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        close.setText("cancel");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(close))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listDBSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDBSelActionPerformed
        // TODO add your handling code here:
        String type = listDBSel.getSelectedItem().toString();
        if (type.equalsIgnoreCase("SqlServer")) {
            DriverNameTxt.setText("net.sourceforge.jtds.jdbc.Driver");
        } else if (type.equalsIgnoreCase("MySQL")) {
            DriverNameTxt.setText("com.mysql.jdbc.Driver");
        } else if (type.equalsIgnoreCase("Oracle")) {
            DriverNameTxt.setText("oracle.jdbc.driver.OracleDriver");
        } else {
            DriverNameTxt.setText("");
        }

    }//GEN-LAST:event_listDBSelActionPerformed

    private void checkButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButActionPerformed
        
        try
        {
            Class.forName(DriverNameTxt.getText()); //specify the jtds driver
            Connection conn = DriverManager.getConnection(connectionTxt.getText()); //establish connection     
            JOptionPane.showMessageDialog(this, "connect success");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "cannnot connect to db");
            e.printStackTrace();
        }

    }//GEN-LAST:event_checkButActionPerformed

    private void serverTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverTxtActionPerformed
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_serverTxtActionPerformed

    private void DBTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBTxtActionPerformed
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_DBTxtActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        clearDialog();
    }//GEN-LAST:event_closeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        Session sessionMap = Session.Getinstance();
        Map<String, Object> parameter = sessionMap.getMap();
        parameter.put("username", userTxt.getText());
        parameter.put("password", passwordTxt.getText());
        parameter.put("connectionString", connectionTxt.getText());
        parameter.put("driverName", DriverNameTxt.getText());
        parameter.put("DBName", DBTxt.getText());
        parameter.put("DBType", listDBSel.getSelectedItem().toString());
        parameter.put("server", serverTxt.getText());
        parameter.put("PORT", portTxt.getText());
        sessionMap.setMap(parameter);
        
        try {

            mainFrame = this.getMainFrame();
            mainFrame.getPackageNameTxt().setText(parameter.get("packagename").toString());
            mainFrame.getProjectNameTxt().setText(parameter.get("projectname").toString());
            mainFrame.getURLTxt().setText(parameter.get("url").toString());
            mainFrame.getPathProjectTxt().setText(parameter.get("projectpath").toString());
            
            mainFrame.getUserTxt().setText(parameter.get("username").toString());
            mainFrame.getDriverTxt().setText(parameter.get("driverName").toString());
            mainFrame.getPassTxt().setText(parameter.get("password").toString());
            mainFrame.getConnectTxt().setText(parameter.get("connectionString").toString());
            SchemaDB Schema = new SchemaDB(parameter.get("DBType").toString(), parameter.get("username").toString(), parameter.get("password").toString(), parameter.get("server").toString(), parameter.get("DBName").toString(), "");
            sessionMap.setSchema(Schema);
            clearDialog();
            this.setVisible(false);
            System.out.println(parameter);
            
        } catch (Exception ex) {
            Logger.getLogger(SetupDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void serverTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverTxtKeyPressed
        // TODO add your handling code here:
        //setConnection(serverTxt.getText(), DBTxt.getText());
    }//GEN-LAST:event_serverTxtKeyPressed

    private void DBTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DBTxtKeyPressed
        // TODO add your handling code here:
        //setConnection(serverTxt.getText(), DBTxt.getText());
    }//GEN-LAST:event_DBTxtKeyPressed

    private void serverTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverTxtKeyReleased
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_serverTxtKeyReleased

    private void DBTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DBTxtKeyReleased
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_DBTxtKeyReleased

    private void portTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portTxtKeyReleased
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_portTxtKeyReleased

    private void userTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTxtKeyReleased
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_userTxtKeyReleased

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        // TODO add your handling code here:
        setConnection(serverTxt.getText(), DBTxt.getText(),userTxt.getText(),passwordTxt.getText(),portTxt.getText());
    }//GEN-LAST:event_passwordTxtKeyReleased

    public void clearDialog() {
        listDBSel.setSelectedIndex(0);
        DriverNameTxt.setText("");
        userTxt.setText("");
        passwordTxt.setText("");
        serverTxt.setText("");
        DBTxt.setText("");
        connectionTxt.setText("");
    }

    public void setConnection(String server, String DBNAME,String user,String pass,String port) {
        String connection = "";  
        if (listDBSel.getSelectedItem().toString().equalsIgnoreCase(Mysql_Name)) {
           connection = "jdbc:mysql://" + server + "/" + DBNAME + "?user=" + user + "&password=" + pass;
        }else if (listDBSel.getSelectedItem().toString().equalsIgnoreCase(Sqlserver_Name)) {
           connection = "jdbc:jtds:sqlserver://" + server + ":" + port + "/" + DBNAME + ";user=" + user + ";password=" + pass;
        }      
        connectionTxt.setText(connection);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DBTxt;
    private javax.swing.JTextField DriverNameTxt;
    private javax.swing.JButton checkBut;
    private javax.swing.JButton close;
    private javax.swing.JTextField connectionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox listDBSel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField portTxt;
    private javax.swing.JTextField serverTxt;
    private javax.swing.JButton submit;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
